### ISSUE TITLE
error: ‘MaybeLocal’ was not declared in this scope 

### ISSUE THREAD

**Issue by theozaurus** [Floobits/node-native-dmp#3]
While installing on Ubuntu 14.04.3

``` bash
$ sudo apt-get install libqt4-dev
$ npm install native-diff-match-patch

> native-diff-match-patch@0.3.1 install /home/pair/.nvm/v0.12.7/lib/node_modules/native-diff-match-patch
> node-gyp rebuild

make: Entering directory `/home/pair/.nvm/v0.12.7/lib/node_modules/native-diff-match-patch/build'
  CXX(target) Release/obj.target/dmp-test/src/diff_match_patch_test.o
  CXX(target) Release/obj.target/dmp-test/src/diff_match_patch.o
  LINK(target) Release/dmp-test
  CXX(target) Release/obj.target/dmp/src/diff_match_patch.o
  CXX(target) Release/obj.target/dmp/src/dmp.o
../src/dmp.cc: In function ‘void PatchApply(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/dmp.cc:118:3: error: ‘MaybeLocal’ was not declared in this scope
   MaybeLocal<Object> mb = node::Buffer::Copy(isolate, result.first, result.first.length());
   ^
../src/dmp.cc:118:20: error: expected primary-expression before ‘>’ token
   MaybeLocal<Object> mb = node::Buffer::Copy(isolate, result.first, result.first.length());
                    ^
../src/dmp.cc:118:22: error: ‘mb’ was not declared in this scope
   MaybeLocal<Object> mb = node::Buffer::Copy(isolate, result.first, result.first.length());
                      ^
../src/dmp.cc:118:27: error: ‘Copy’ is not a member of ‘node::Buffer’
   MaybeLocal<Object> mb = node::Buffer::Copy(isolate, result.first, result.first.length());
                           ^
make: *** [Release/obj.target/dmp/src/dmp.o] Error 1
make: Leaving directory `/home/pair/.nvm/v0.12.7/lib/node_modules/native-diff-match-patch/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pair/.nvm/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-57-generic
gyp ERR! command "node" "/home/pair/.nvm/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pair/.nvm/v0.12.7/lib/node_modules/native-diff-match-patch
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Linux 3.13.0-57-generic
npm ERR! argv "/home/pair/.nvm/v0.12.7/bin/node" "/home/pair/.nvm/v0.12.7/bin/npm" "install" "-g" "native-diff-match-patch"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! native-diff-match-patch@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the native-diff-match-patch@0.3.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the native-diff-match-patch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls native-diff-match-patch
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pair/workspace/gfwd/npm-debug.log
```

What versions of libraries do we need to get this working?

**Comment by ggreer** [comment]
Qt5 & pkg-config. Check .travis.yml for the dependencies.
